export const classificationLookup = {
  'RULEUC_Engineer': 'Build',
  'RULEUC_Commander': 'Build',
  'RULEUMT_Amphibious': 'Land',
  'RULEUC_MilitaryVehicle': 'Land',
  'RULEUC_MilitaryAircraft': 'Air',
  'RULEUC_MilitarySub': 'Naval',
  'RULEUC_MilitaryShip': 'Naval',
  'RULEUC_Weapon': 'Base',
  'RULEUC_Sensor': 'Base',
  'RULEUC_Factory': 'Base',
  'RULEUC_MilitaryStructure': 'Base',
  'RULEUC_Resource': 'Base',
  'RULEUC_MiscSupport': 'Base',
  'RULEUC_CounterMeasure': 'Base'
}

export const techLookup = {
  'TECH1': 'T1',
  'TECH2': 'T2',
  'TECH3': 'T3',
  'EXPERIMENTAL': 'EXP'
}

export const factionIdLookup = {
  'UEF': 0,
  'Cybran': 1,
  'Aeon': 2,
  'Seraphim': 3,
  'Nomads': 4
}

export const detailedClassificationById = {
  'ZEB9601': 'T3 Land Factory',
  'XEB0204': 'T2 Engineering Station',
  'UEL0401': 'Direct Fire Experimental',
  'UAL0401': 'Direct Fire Experimental',
  'XSL0401': 'Direct Fire Experimental',
  'URL0402': 'Direct Fire Experimental',
  'XNL0402': 'Direct Fire Experimental',
  'XRL0403': 'Direct Fire Experimental',
  'URA0401': 'Air Experimental',
  'XRL0401': 'Air Experimental',
  'UAA0310': 'Air Experimental',
  'XSA0402': 'Air Experimental',
  'XNA0401': 'Air Experimental',
  'UES0401': 'Naval Experimental',
  'UAS0401': 'Naval Experimental',
  'UEB2401': 'Indirect Fire Experimental',
  'XNL0403': 'Indirect Fire Experimental',
  'URL0401': 'Indirect Fire Experimental',
  'XSB2401': 'Indirect Fire Experimental',
  'XAB2307': 'Indirect Fire Experimental',
  'XAB1401': 'Other Experimental',
  'XNO0001': 'Other Experimental',
  'XEA0002': 'Other Experimental',
  'XEB2402': 'Other Experimental',
  'XNA0107': 'T1 Light Air Transport',
  'XNA0203': 'T2 Gunship',
  'UEA0003': 'ACU Engineering Drone',
  'UEL0201': 'T1 Bot/Tank',
  'URL0107': 'T1 Bot/Tank',
  'UAL0201': 'T1 Bot/Tank',
  'XSL0201': 'T1 Bot/Tank',
  'XNL0201': 'T1 Bot/Tank',
  'XSL0101': 'T1 Land Scout',
  'XNL0106': 'T1 Light Assault Bot',
  'XNL0103': 'T1 Mobile Light Artillery',
  'XNL0107': 'T1 Tank Destroyer',
  'UEL0202': 'T2 Heavy Tank/Assault Bot',
  'URL0202': 'T2 Heavy Tank/Assault Bot',
  'UAL0202': 'T2 Heavy Tank/Assault Bot',
  'XSL0202': 'T2 Heavy Tank/Assault Bot',
  'DRL0204': 'T2 Bot',
  'DEL0204': 'T2 Bot',
  'UEL0203': 'T2 Hover/Amphibious Tank',
  'XAL0203': 'T2 Hover/Amphibious Tank',
  'XSL0203': 'T2 Hover/Amphibious Tank',
  'XNL0203': 'T2 Hover/Amphibious Tank',
  'URL0203': 'T2 Hover/Amphibious Tank',
  'XEL0305': 'T3 Main Assault Bot/Tank',
  'XRL0305': 'T3 Main Assault Bot/Tank',
  'UAL0303': 'T3 Main Assault Bot/Tank',
  'XSL0303': 'T3 Main Assault Bot/Tank',
  'XNL0305': 'T3 Main Assault Bot/Tank',
  'UEL0303': 'T3 Assault Bot',
  'URL0303': 'T3 Assault Bot',
  'XNL0303': 'T3 Assault Bot',
  'UEL0104': 'T1 Mobile Anti-Air',
  'URL0104': 'T1 Mobile Anti-Air',
  'UAL0104': 'T1 Mobile Anti-Air',
  'XSL0104': 'T1 Mobile Anti-Air',
  'XSB2104': 'T1 Anti-Air Turret',
  'XNB2202': 'T2 Anti-Air Flak Artillery',
  'URL0205': 'T2 Mobile Anti-Air',
  'UAL0205': 'T2 Mobile Anti-Air',
  'UEL0205': 'T2 Mobile Anti-Air',
  'XSL0205': 'T2 Mobile Anti-Air',
  'XNL0205': 'T2 Mobile Anti-Air',
  'DELK002': 'T3 Mobile Anti-Air',
  'DSLK004': 'T3 Mobile Anti-Air',
  'DRLK001': 'T3 Mobile Anti-Air',
  'DALK003': 'T3 Mobile Anti-Air',
  'XNL0302': 'T3 Mobile Anti-Air',
  'UAS0102': 'T1 Anti-Air Boat',
  'XNS0102': 'T2 Torpedo Boat',
  'XRS0204': 'T2 Submarine',
  'XAS0204': 'T2 Submarine',
  'XNB1102': 'T1 Hydrocarbon Power Plant',
  'XNB0304': 'T3 Quantum Gateway',
  'XSB5202': 'T1 Air Staging Facility',
  'XNB5202': 'T1 Air Staging Facility',
  'XNB2207': 'T2 Torpedo Launcher',
  'XNO2302': 'T3 Heavy Artillery Installation',
  'XAA0305': 'T3 Anti-Air Gunship',
  'XSB2304': 'T3 Anti-Air SAM Launcher',
  'XSB3104': 'T3 Omni Sensor Array',
  'XNB4202': 'T2 Shield Generator',
  'URB4207': 'T3 Heavy Shield Generator',
  'XNB5101': 'T1 Wall Section',
  'XNA0303': 'T3 Air Superiority Fighter'
}

export const categoryDefinitions = {
  'Construction - Buildpower': ['T1 Engineer', 'T2 Engineer', 'T2 Field Engineer', 'T3 Engineer', 'T3 Support Armored Command Unit', 'Armored Command Unit', 'ACU Engineering Drone', 'T1 Engineering Drone', 'T2 Engineering Drone', 'T2 Engineering Station', 'T3 Engineering Station'],
  'Land': ['T1 Bot/Tank', 'T1 Light Assault Bot', 'T1 Light Assault Vehicle', 'T1 Mobile Light Artillery', 'T1 Tank Destroyer', 'T1 Mobile Anti-Air', 'T1 Land Scout', 'T2 Heavy Tank/Assault Bot', 'T2 Hover/Amphibious Tank', 'T2 EMP Tank', 'T2 Bot', 'T2 Mobile Missile Launcher', 'T2 Mobile Anti-Air', 'T2 Mobile Shield Generator', 'T2 Mobile Stealth Field System', 'T2 Mobile Bomb', 'T2 Crab Egg (Flak)', 'T3 Main Assault Bot/Tank', 'T3 Assault Bot', 'T3 Sniper Bot', 'T3 Mobile Heavy Artillery', 'T3 Mobile Missile Platform', 'T3 Mobile Anti-Air', 'T3 Mobile Shield Generator', 'T3 Shield Disruptor', 'T3 Crab Egg (Engineer)', 'T3 Crab Egg (Brick)', 'T3 Crab Egg (Artillery)', 'T3 Crab Egg (Bouncer)'],
  'Air': ['T1 Interceptor', 'T1 Attack Bomber', 'T1 Light Gunship', 'T1 Air Scout', 'T1 Light Air Transport', 'T2 Combat Fighter', 'T2 Fighter/Bomber', 'T2 Gunship', 'T2 Torpedo Bomber', 'T2 Guided Missile', 'T2 Air Transport', 'T3 Air Superiority Fighter', 'T3 Strategic Bomber', 'T3 Heavy Gunship', 'T3 Anti-Air Gunship', 'T3 Torpedo Bomber', 'T3 Spy Plane', 'T3 Heavy Air Transport'],
  'Naval': ['T1 Attack Submarine', 'T1 Frigate', 'T1 Anti-Air Boat', 'T2 Submarine', 'T2 Destroyer', 'T2 Cruiser', 'T2 Torpedo Boat', 'T2 Shield Boat', 'T2 Counter-Intelligence Boat', 'T3 Submarine Hunter', 'T3 Battleship', 'T3 Strategic Missile Submarine', 'T3 Tactical Submarine', 'T3 Aircraft Carrier', 'T3 Battlecruiser', 'T3 Missile Ship'],
  'Experimental': ['Direct Fire Experimental', 'Air Experimental', 'Naval Experimental', 'Indirect Fire Experimental', 'Other Experimental'],
  'Structures - Weapons': ['T1 Point Defense', 'T1 Anti-Air Turret', 'T1 Torpedo Launcher', 'T2 Point Defense', 'T2 Anti-Air Flak Artillery', 'T2 Torpedo Launcher', 'T2 Artillery Installation', 'T2 Tactical Missile Launcher', 'T2 Tactical Missile Defense', 'T3 Heavy Point Defense', 'T3 Anti-Air SAM Launcher', 'T3 Torpedo Ambushing System', 'T3 Heavy Artillery Installation', 'T3 Rocket Artillery Installation', 'T3 Rapid-Fire Artillery Installation', 'T3 Strategic Missile Launcher', 'T3 Strategic Missile Defense'],
  'Structures - Support': ['T1 Wall Section', 'T1 Air Staging Facility', 'T2 Shield Generator', 'T2 Shield Generator: ED2', 'T2 Shield Generator: ED3', 'T2 Stealth Shield Generator', 'T3 Shield Generator', 'T2 Shield Generator: ED4', 'T2 Shield Generator: ED5', 'T3 Heavy Shield Generator', 'T3 Heavy Stealth Shield Generator'],
  'Structures - Intelligence': ['T1 Radar System', 'T1 Sonar System', 'T2 Radar System', 'T2 Sonar System', 'T2 Stealth Field Generator', 'T3 Omni Sensor Array', 'T3 Sonar Platform', 'T3 Perimeter Monitoring System', 'T3 Quantum Optics Facility'],
  'Structures - Economy': ['T1 Mass Extractor', 'T1 Power Generator', 'T1 Hydrocarbon Power Plant', 'T1 Energy Storage', 'T1 Mass Storage', 'T2 Mass Extractor', 'T2 Power Generator', 'T2 Mass Fabricator', 'T3 Mass Extractor', 'T3 Power Generator', 'T3 Mass Fabricator'],
  'Structures - Factories': ['T1 Land Factory', 'T1 Air Factory', 'T1 Naval Factory', 'T2 Land Factory HQ', 'T2 Land Factory', 'T2 Air Factory HQ', 'T2 Air Factory', 'T2 Naval Factory HQ', 'T2 Naval Factory', 'T3 Land Factory HQ', 'T3 Land Factory', 'T3 Air Factory HQ', 'T3 Air Factory', 'T3 Naval Factory HQ', 'T3 Naval Factory', 'T3 Quantum Gateway']
}
